import { LitElement, css, html } from 'lit'
import './tree-graph'
import { type LayoutOptions, type TreeGraphData, type TreePersonData } from './tree-graph'
import { layoutFamilyBlocks } from './tree-layout'

type TreeMode = 'close' | 'ancestors' | 'descendants' | 'mixed' | 'path' | 'all'
const modes: { id: TreeMode; label: string }[] = [{ id: 'close', label: 'Ближайшие' }, { id: 'ancestors', label: 'Предки' }, { id: 'descendants', label: 'Потомки' }, { id: 'mixed', label: 'Смешанное' }, { id: 'path', label: 'Как связаны' }, { id: 'all', label: 'Вся семья' }]
const CONTROLS_CLEARANCE = 160
const DRAG_THRESHOLD = 6
const INSPECTOR_WIDTH = 320
const INSPECTOR_HEIGHT = 166

export class CatsTreePage extends LitElement {
  static properties = { rootId: { attribute: false }, mode: { state: true }, depth: { state: true }, direction: { state: true }, zoom: { state: true }, panX: { state: true }, panY: { state: true }, tree: { state: true }, error: { state: true }, selectedId: { state: true }, relatedTo: { state: true }, showBands: { state: true }, focusHistory: { state: true }, treeSearch: { state: true }, compactDepth: { state: true }, expandedBlockIds: { state: true } }
  declare rootId: string | null; private declare mode: TreeMode; private declare depth: number; private declare direction: LayoutOptions['direction']; private declare zoom: number; private declare panX: number; private declare panY: number; private declare tree: TreeGraphData | null; private declare error: boolean; private declare selectedId: string | null; private declare relatedTo: string | null; private declare showBands: boolean; private declare focusHistory: string[]; private declare treeSearch: string; private declare compactDepth: number; private declare expandedBlockIds: string[]; private drag: { x: number; y: number; panX: number; panY: number; didDrag: boolean } | null = null; private suppressNextSelection = false
constructor() { super(); const params = new URLSearchParams(window.location.search); const requestedMode = params.get('mode'); this.rootId = null; this.mode = isTreeMode(requestedMode) ? requestedMode : 'mixed'; this.depth = clamp(Number(params.get('depth')) || 2, 1, 5); this.direction = params.get('dir') === 'h' ? 'horizontal' : 'vertical'; this.zoom = 1; this.panX = 0; this.panY = 0; this.tree = null; this.error = false; this.selectedId = null; this.relatedTo = params.get('to'); this.showBands = true; this.focusHistory = []; this.treeSearch = ''; this.compactDepth = 2; this.expandedBlockIds = [] }
  static styles = css`
    :host { display:block; min-height:calc(100vh - 4.5rem); color:#171817; } .workspace { min-height:calc(100vh - 4.5rem); display:flex; flex-direction:column; } .heading { padding:1.5rem clamp(1rem,3vw,3rem) .75rem; } h1 { margin:0; font:400 clamp(2rem,4vw,3.5rem) Iowan Old Style,Georgia,serif; }
    .stage { position:relative; flex:1; min-height:42rem; overflow:hidden; touch-action:none; background-color:#fbfbf9; background-image:radial-gradient(#dfe1da 1px,transparent 1px); background-size:16px 16px; border-top:1px solid #d7d8d2; cursor:grab; } .stage.dragging { cursor:grabbing; } .scene { position:absolute; left:0; top:0; transform-origin:0 0; transition:transform 160ms ease; } .stage.dragging .scene { transition:none; }
    .controls { position:absolute; z-index:2; left:16px; right:16px; top:16px; display:flex; align-items:flex-start; justify-content:space-between; gap:12px; pointer-events:none; } .control-left,.control-right,.modes,.bottom { display:flex; align-items:center; gap:4px; background:#fff; border:1px solid #dcdcd8; border-radius:3px; padding:4px; pointer-events:auto; } .control-left { padding:6px 10px; gap:10px; } .control-right { flex-wrap:wrap; justify-content:flex-end; } .modes { margin-right:auto; } .focus-label { font-size:12px; color:#6b6d69; } .focus-label strong { display:block; color:#171817; font-size:13px; }
    button { min-height:34px; border:0; background:transparent; color:#171817; padding:0 11px; font:500 13px Inter,system-ui,sans-serif; cursor:pointer; border-radius:2px; } button:hover,button:focus-visible { background:#e4ece7; color:#1b3f31; } button[aria-pressed="true"],.primary { background:#24513f; color:#fff; } button:disabled { opacity:.45; cursor:default; } .counter { min-width:18px; text-align:center; font-size:13px; } .bottom { position:absolute; z-index:2; right:16px; bottom:16px; padding:4px; } .bottom button { min-height:36px; } .percent { min-width:46px; text-align:center; font-size:12px; color:#4a4c49; }
    .inspector { position:absolute; z-index:3; width:min(20rem,calc(100% - 2rem)); padding:12px; background:#fff; border:1px solid #dcdcd8; border-radius:3px; box-shadow:0 8px 20px rgba(23,24,23,.12); } .inspector-header { display:flex; justify-content:space-between; align-items:flex-start; gap:8px; } .inspector strong { display:block; font:400 20px Iowan Old Style,Georgia,serif; } .inspector p { margin:4px 0 12px; color:#6b6d69; font-size:13px; } .inspector-actions { display:flex; gap:5px; flex-wrap:wrap; } .close-inspector { min-height:24px; padding:0 5px; font-size:18px; } .tree-search { position:absolute; z-index:3; left:16px; bottom:16px; width:min(20rem,calc(100% - 2rem)); } .tree-search input { box-sizing:border-box; width:100%; min-height:36px; padding:0 10px; border:1px solid #dcdcd8; border-radius:3px; background:#fff; font:13px Inter,system-ui,sans-serif; } .tree-search-results { max-height:12rem; overflow:auto; margin-top:4px; background:#fff; border:1px solid #dcdcd8; } .tree-search-results button { display:block; width:100%; text-align:left; } .error { position:absolute; z-index:3; inset:7rem auto auto 1rem; padding:1rem; background:#fff; border:1px solid #a3402c; color:#7d2b20; } .hint { position:absolute; z-index:2; left:16px; bottom:16px; background:#fff; border:1px solid #dcdcd8; padding:.75rem; } @media(max-width:50rem) { .controls { flex-wrap:wrap; } .modes { order:3; margin-right:0; overflow:auto; max-width:100%; } .control-right { margin-left:auto; } .stage { min-height:34rem; } }
  `
  connectedCallback() { super.connectedCallback(); void this.loadTree() }
  updated(changed: Map<string, unknown>) { if (changed.has('rootId') && this.isConnected) void this.loadTree() }
  private async loadTree() { if (!this.rootId || (this.mode === 'path' && !this.relatedTo)) return; this.error = false; const params = new URLSearchParams({ mode:this.mode, depth:String(this.depth) }); if (this.mode === 'path' && this.relatedTo) params.set('to',this.relatedTo); try { const response = await fetch(`/api/v1/tree/${this.rootId}?${params}`); if (!response.ok) throw new Error(); this.tree = await response.json(); this.selectedId = null; await this.updateComplete; requestAnimationFrame(() => this.fit()) } catch { this.tree=null; this.error=true } }
  private async selectMode(mode:TreeMode) { this.mode=mode; this.compactDepth=2; this.expandedBlockIds=[]; if(mode!=='path') this.relatedTo=null; this.syncUrl(); await this.loadTree() }
  private async adjustDepth(delta:number) { this.depth=clamp(this.depth+delta,1,5); this.syncUrl(); await this.loadTree() }
  private setDirection(direction:LayoutOptions['direction']) { this.direction=direction; this.syncUrl(); this.fit() }
  private syncUrl() { if(!this.rootId) return; const params=new URLSearchParams({person:this.rootId,mode:this.mode,depth:String(this.depth)}); if(this.direction==='horizontal') params.set('dir','h'); if(this.mode==='path'&&this.relatedTo) params.set('to',this.relatedTo); history.replaceState({},'',`/tree?${params}`) }
  private onPersonSelect(event:CustomEvent<{personId:string}>) { if(this.suppressNextSelection) { this.suppressNextSelection=false; return } const id=event.detail.personId; if(this.mode==='path'&&id!==this.rootId) { this.relatedTo=id; this.syncUrl(); void this.loadTree(); return } this.selectedId=id }
  private onPersonCenter(event:CustomEvent<{personId:string}>) { this.selectedId=event.detail.personId; this.makeCenter(event.detail.personId) }
  private onContinuationSelect(event:CustomEvent<{blockId:string;sourcePersonId?:string}>) { if(this.mode!=='all'&&event.detail.sourcePersonId) { this.mode='all'; this.rootId=event.detail.sourcePersonId; this.expandedBlockIds=[]; this.syncUrl(); void this.loadTree(); return } this.expandedBlockIds=[...new Set([...this.expandedBlockIds,event.detail.blockId])] }
  private currentPerson():TreePersonData|null { return this.tree?.people.find(person=>person.id===this.selectedId)??null }
  private makeCenter(personId=this.selectedId) { const person=this.tree?.people.find(item=>item.id===personId)??null; if(!person||person.is_hidden||person.id===this.rootId)return; if(this.rootId)this.focusHistory=[...this.focusHistory,this.rootId]; this.rootId=person.id; this.selectedId=person.id; this.relatedTo=null; this.syncUrl(); void this.loadTree() }
  private goBack() { const previous=this.focusHistory.at(-1); if(!previous)return; this.focusHistory=this.focusHistory.slice(0,-1); this.rootId=previous; this.selectedId=previous; this.syncUrl(); void this.loadTree() }
  private fit() { const stage=this.shadowRoot?.querySelector('.stage') as HTMLElement|null; if(!stage||!this.tree||!stage.clientWidth||!stage.clientHeight) { this.zoom=.82; this.panX=0; this.panY=CONTROLS_CLEARANCE; return } const bounds=layoutFamilyBlocks(this.tree,{direction:this.direction,collapseDistant:this.mode==='all',compactDepth:this.compactDepth,expandedBlockIds:this.expandedBlockIds}); const availableWidth=Math.max(1,stage.clientWidth-32); const availableHeight=Math.max(1,stage.clientHeight-CONTROLS_CLEARANCE-32); this.zoom=clamp(Math.min(availableWidth/bounds.width,availableHeight/bounds.height),.3,1.6); this.panX=Math.max(16,(stage.clientWidth-bounds.width*this.zoom)/2); this.panY=CONTROLS_CLEARANCE+Math.max(16,(availableHeight-bounds.height*this.zoom)/2) }
  private zoomBy(factor:number) { this.zoom=clamp(this.zoom*factor,.3,1.6) }
  private onWheel(event:WheelEvent) { if(!event.ctrlKey&&!event.metaKey)return; event.preventDefault(); const before=this.zoom; this.zoom=clamp(this.zoom*Math.exp(-event.deltaY*.01),.3,1.6); const rect=(event.currentTarget as HTMLElement).getBoundingClientRect(); const ratio=this.zoom/before; this.panX=event.clientX-rect.left-(event.clientX-rect.left-this.panX)*ratio; this.panY=event.clientY-rect.top-(event.clientY-rect.top-this.panY)*ratio }
  private pointerDown(event:PointerEvent) { if(event.composedPath().some(node=>node instanceof Element&&node.matches('.controls,.bottom,.inspector,.tree-search,a')))return; this.suppressNextSelection=false; this.drag={x:event.clientX,y:event.clientY,panX:this.panX,panY:this.panY,didDrag:false}; (event.currentTarget as HTMLElement).setPointerCapture?.(event.pointerId) }
  private pointerMove(event:PointerEvent) { if(!this.drag)return; const dx=event.clientX-this.drag.x; const dy=event.clientY-this.drag.y; if(!this.drag.didDrag&&Math.hypot(dx,dy)<=DRAG_THRESHOLD)return; this.drag.didDrag=true; this.requestUpdate(); this.panX=this.drag.panX+dx; this.panY=this.drag.panY+dy }
  private pointerUp() { if(this.drag?.didDrag) { this.suppressNextSelection=true; setTimeout(()=>{this.suppressNextSelection=false},0) } this.drag=null; this.requestUpdate() }
  private closeOnEscape(event:KeyboardEvent) { if(event.key==='Escape'&&this.selectedId) { event.stopPropagation(); this.selectedId=null } }
  private closeOnCanvas(event:MouseEvent) { const keepOpen = event.composedPath().some((node) => node instanceof Element && node.matches('.card,.inspector,.controls,.bottom')); if (!keepOpen) this.selectedId=null }
  private inspectorPosition(person:TreePersonData) { const stage=this.shadowRoot?.querySelector('.stage') as HTMLElement|null; const bounds=stage?.getBoundingClientRect(); const node=this.tree?layoutFamilyBlocks(this.tree,{direction:this.direction,collapseDistant:this.mode==='all',compactDepth:this.compactDepth,expandedBlockIds:this.expandedBlockIds}).nodes[person.id]:null; if(!bounds||!node)return 'left:16px;top:16px'; const x=this.panX+node.x*this.zoom; const y=this.panY+node.y*this.zoom; const cardWidth=node.width*this.zoom; const left=Math.max(8,Math.min(bounds.width-INSPECTOR_WIDTH-8,x+cardWidth+12>bounds.width-8?x-INSPECTOR_WIDTH-12:x+cardWidth+12)); const top=Math.max(8,Math.min(bounds.height-INSPECTOR_HEIGHT-8,y)); return `left:${left}px;top:${top}px` }
  render() { if(!this.rootId)return html`<section class="workspace"><div class="heading"><h1>Семейное дерево</h1><p>Откройте карточку человека и выберите «Открыть дерево».</p></div></section>`; const person=this.currentPerson(); const noLinks=this.tree&&!this.tree.parent_links.length&&!this.tree.unions.length; const searchResults=this.mode==='all'&&this.treeSearch ? this.tree?.people.filter(item=>!item.is_hidden&&item.display_name?.toLocaleLowerCase('ru').includes(this.treeSearch.toLocaleLowerCase('ru'))).slice(0,12)??[] : []; return html`<section class="workspace"><div class="heading"><h1>Семейное дерево</h1></div><div class="stage ${this.drag?.didDrag?'dragging':''}" tabindex="0" @keydown=${this.closeOnEscape} @click=${this.closeOnCanvas} @wheel=${this.onWheel} @pointerdown=${this.pointerDown} @pointermove=${this.pointerMove} @pointerup=${this.pointerUp} @pointercancel=${this.pointerUp}>
      <div class="controls"><div class="control-left"><button ?disabled=${!this.focusHistory.length} @click=${this.goBack} aria-label="Вернуться к предыдущему центру">←</button><span class="focus-label">В ЦЕНТРЕ<strong>${this.tree?.people.find(p=>p.is_root)?.display_name??'Загрузка…'}</strong></span></div><div class="modes">${modes.map(({id,label})=>html`<button aria-pressed=${String(this.mode===id)} @click=${()=>this.selectMode(id)}>${label}</button>`)}</div><div class="control-right"><span class="focus-label">Поколений</span><button ?disabled=${this.depth===1||this.mode==='close'||this.mode==='path'||this.mode==='all'} @click=${()=>this.adjustDepth(-1)}>−</button><span class="counter">${this.depth}</span><button ?disabled=${this.depth===5||this.mode==='close'||this.mode==='path'||this.mode==='all'} @click=${()=>this.adjustDepth(1)}>+</button><button aria-pressed=${String(this.direction==='vertical')} @click=${()=>this.setDirection('vertical')}>↓ Вниз</button><button aria-pressed=${String(this.direction==='horizontal')} @click=${()=>this.setDirection('horizontal')}>→ Вправо</button><button aria-pressed=${String(this.showBands)} @click=${()=>{this.showBands=!this.showBands}}>Полосы поколений</button></div></div>
      ${this.error?html`<div class="error"><p>Не удалось загрузить ветвь. Проверьте соединение и повторите попытку.</p><button class="primary" @click=${this.loadTree}>Повторить</button></div>`:''}${noLinks?html`<p class="hint">У этого человека в архиве нет родственников.</p>`:''}${this.mode==='path'&&!this.relatedTo?html`<p class="hint">Выберите второго человека, чтобы увидеть цепочку родства.</p>`:''}
      ${this.tree&&!this.error?html`<div class="scene" style="transform:translate(${this.panX}px,${this.panY}px) scale(${this.zoom})"><cats-tree-graph .graph=${this.tree} .direction=${this.direction} .selectedId=${this.selectedId} .showBands=${this.showBands} .collapseDistant=${this.mode==='all'} .compactDepth=${this.compactDepth} .expandedBlockIds=${this.expandedBlockIds} @person-select=${this.onPersonSelect} @person-center=${this.onPersonCenter} @continuation-select=${this.onContinuationSelect}></cats-tree-graph></div>`:''}${this.mode==='all'?html`<div class="tree-search"><input aria-label="Найти человека в семье" .value=${this.treeSearch} @input=${(event:InputEvent)=>{this.treeSearch=(event.target as HTMLInputElement).value}} placeholder="Найти человека">${searchResults.length?html`<div class="tree-search-results">${searchResults.map(item=>html`<button @click=${()=>{this.treeSearch='';this.makeCenter(item.id)}}>${item.display_name}</button>`)}</div>`:''}</div>`:''}
      <div class="bottom"><button aria-label="Уменьшить масштаб" @click=${()=>this.zoomBy(1/1.2)}>−</button><span class="percent">${Math.round(this.zoom*100)}%</span><button aria-label="Увеличить масштаб" @click=${()=>this.zoomBy(1.2)}>+</button><button @click=${this.fit}>Вписать</button><button @click=${()=>{this.panX=0;this.panY=CONTROLS_CLEARANCE}}>К центру</button></div>
      ${person?html`<aside class="inspector" style=${this.inspectorPosition(person)} aria-label="Карточка выбранного человека"><div class="inspector-header"><strong>${person.is_hidden?'Сведения скрыты':person.display_name}</strong><button class="close-inspector" aria-label="Закрыть карточку" @click=${()=>{this.selectedId=null}}>×</button></div>${!person.is_hidden?html`<p>${[person.birth_label,person.death_label].filter(Boolean).join(' – ')||'Даты не указаны'}</p>${person.relationship?.reason?html`<p>Почему так: ${person.relationship.reason}</p>`:''}<div class="inspector-actions"><button class="primary" ?disabled=${person.id===this.rootId} @click=${()=>this.makeCenter()}>Сделать центром</button><a href="/people/${person.id}">Открыть страницу</a></div>`:''}</aside>`:''}</div></section>` }
}
function clamp(value:number,min:number,max:number){return Math.min(max,Math.max(min,value))} function isTreeMode(value:string|null):value is TreeMode{return modes.some(mode=>mode.id===value)}
customElements.define('cats-tree-page',CatsTreePage)
